package cz.cvut.fel.nutforms.example.model.Bug.new;

import cz.cvut.fel.nutforms.example.model.Bug;

dialect  "mvel"

//rule "[Bug] Has description"
//    when
//        Bug(description != null && description != "")
//    then
//end
//
//rule "[Bug] Is log valid"
//    when
//        Bug(log != null && log != "")
//        Bug(log.length() < 50)
//    then
//end

rule "[Bug] Is description null"
    when
        Bug(description != null)
    then
end

rule "[Bug] Is description long enough"
    when
        Bug(description.length > 15)    // length vs length()
    then
end
