package cz.cvut.fel.nutforms.example.model.Bug.new;

import cz.cvut.fel.nutforms.example.model.Bug;

dialect  "mvel"

rule "[Bug] Is description properly long"
    when
        Bug(description != null && description.length > 14 && description.length < 31)    // length vs length()
    then
end

rule "[Bug] Is log filled in"
    when
        Bug(log != null && log.trim().length > 0)   // trim() should be valid in Drools
    then
end

// regex test
rule "[Bug] Is alphanumeric"
    when
        Bug(description matches "^[a-zA-Z0-9 ]*$")
    then
end

// number test
//rule "Test"
//    when
//        Bug(log matches "^[0-9]*$" && log > 5 && log < 10)
//    then
//end